### ISSUE TITLE
猜语音只能一个群同时玩，其他群共CD

### ISSUE THREAD

**Issue by yuuki-nya** [GWYOG/HoshinoBotVoiceGuessPlugin#1]
现阶段将m4a转成silk可用，但只能一个群同时玩，其他群共CD。

**Comment by GWYOG** [comment]
是的，猜语音我最早写的小游戏插件，当时由于只在自己公会群里使用所以没考虑到这点。
后来发生8.2事件+mirai发送语音功能缺失，这个小游戏插件代码一直没来得及重构(其他基于Mirai开发的小游戏都修复了)。
本来准备等咖啡佬更新hoshinobot以及等go-cqhttp支持全格式语音后再重构的..不过现在看起来还要等很久，这两天抽空我重构下吧。

**Comment by yuuki-nya** [comment]
> 是的，猜语音我最早写的小游戏插件，当时由于只在自己公会群里使用所以没考虑到这点。
> 后来发生8.2事件+mirai发送语音功能缺失，这个小游戏插件代码一直没来得及重构(其他基于Mirai开发的小游戏都修复了)。
> 本来准备等咖啡佬更新hoshinobot以及等go-cqhttp支持全格式语音后再重构的..不过现在看起来还要等很久，这两天抽空我重构下吧。

非常感谢提供这么有意思的游戏插件:) , 这里有个个人的建议就是降3个猜谜游戏整合，因为有些人喜欢猜人物、猜头像同时启动，这样会造成混乱，将3个猜谜游戏整合或者共CD会好一点。

**Comment by GWYOG** [comment]
谢谢你的建议~想了下确实在大群中使用这几个插件容易误同时启动。

从代码上解决这个问题并不复杂，不过目前这几个插件的情况比较复杂：猜头像和猜角色插件的代码已被HoshinoBot的作者重构并即将合并进HoshinoBot的本体，之前他给我看的重构后的代码里这两个小游戏CD并不共用。如果HoshinoBot里面的小游戏代码框架不支持共CD的话，重构后的猜语音插件也没法和它们共CD。

还有一个解决办法是我自己再重构一下目前的猜头像和猜角色代码，并把猜语音并入。这部分重复工作比较多，想了下还是暂时搁置，看看HoshinoBot那儿的情况再做决定。

**Comment by GWYOG** [comment]
代码已重构完毕，支持多群并改成和猜头像和猜角色一样的抢答+排行榜模式了，使用方法参见README。

更新后第一次使用时可能会下载新的语音(8月31号干炸里脊资源站更新了晶姐的"cygames"语音)，如果有新的自动下载注意转换成silk格式。

几个小游戏插件共CD的建议我会继续考虑，如果什么时候时机合适会去做的 :)

**Comment by GWYOG** [comment]
@seaples 关于多个小游戏会共同启动的问题我靠新的插件解决了，可以看一下[我另一个代码仓库](https://github.com/GWYOG/GWYOG-Hoshino-plugins)的anticoncurrency插件。如果装有赛马或者其他小游戏插件的话，使用anticoncurrency插件理论上应该能一并共CD.
